#!/bin/bash

echo "Settings:"
echo "========="
echo "Domain:"
echo $MAILSERVER_DOMAIN


echo "continue? (y/n)"
read continue


if [[ $continue = y ]]
then

echo "Starting install_backend installation"
cd
cd mailserver



echo "Setting frontend config======================="
sudo cat > public/config/config.json << EOL
{
    "api": {
        "url": "https://api.mailserver.$MAILSERVER_DOMAIN"
    }
}
EOL
echo "Setting frontend config done=================="



echo "Installing and building frontend=============="
npm install
npm run build
npm run build
echo "Building frontend complete===================="



echo "Setting up frontend nginx====================="
sudo cat > /etc/nginx/conf.d/mailserver.$MAILSERVER_DOMAIN.conf << EOL
server {
    listen 443 ssl http2;
    server_name mailserver.$MAILSERVER_DOMAIN;

    location / {
        root /home/$USER/mailserver/dist;
        index index.html;
        try_files \$uri \$uri/ /index.html;
    }

    access_log /var/log/mailserver.${MAILSERVER_DOMAIN}_access.log;
    error_log /var/log/mailserver.${MAILSERVER_DOMAIN}_error.log;

    ssl_certificate /etc/letsencrypt/live/mailserver.$MAILSERVER_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mailserver.$MAILSERVER_DOMAIN/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
    ssl_ecdh_curve secp521r1:secp384r1:prime256v1;

}
server {
    server_name mailserver.$MAILSERVER_DOMAIN;
    return 301 https://\$host\$request_uri;
}
EOL
sudo service nginx reload
echo "Setting up frontend nginx complete============"



else

echo "Cancelling installation."

fi

cd
cd mailserver
