#!/bin/bash


echo "Settings:"
echo "========="
echo "Domain:"
echo $MAILSERVER_DOMAIN
echo "mailuser password:"
echo $MAILSERVER_MAILUSER_PASSWORD


echo "Settings:"
echo "====="
echo "Mail domain:"
echo $website
echo "mailuser (db) password:"
echo $pwd


echo "continue? (y/n)"
read continue


if [[ $continue = y ]]
then

echo "Starting install_backend installation"
cd
cd mailserver



echo "Configuring postfix==========================="
sudo cat > /etc/postfix/main.cf << EOL
myhostname = $MAILSERVER_DOMAIN
mydomain = \$myhostname
smtpd_banner = \$myhostname ESMTP \$mail_name (\$mail_version)

# Domain for outbound mail
myorigin = \$myhostname
# What domains to recieve mail from
mydestination = localhost

# Delivery method: direct
relayhost =
# Trusted SMPT clients
mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
# Network interfaces/protocols
inet_interfaces = all
inet_protocols = all

# Do NOT append @$MAILSERVER_DOMAIN to sent emails, this is the MUA's job
append_dot_mydomain = no
# Compatibility level
compatibility_level = 2

# Mailbox unlimited size
mailbox_size_limit = 0
# Do not notify system of new mail
biff = no

# TLS parameters
smtpd_tls_cert_file=/etc/letsencrypt/live/$MAILSERVER_DOMAIN/fullchain.pem
smtpd_tls_key_file=/etc/letsencrypt/live/$MAILSERVER_DOMAIN/privkey.pem
smtpd_use_tls=yes
smtpd_tls_auth_only = yes
smtp_tls_security_level = may
smtpd_tls_security_level = may
smtpd_sasl_security_options = noanonymous, noplaintext
smtpd_sasl_tls_security_options = noanonymous

# Authentication
smtpd_sasl_type = dovecot
smtpd_sasl_path = private/auth
smtpd_sasl_auth_enable = yes

# Restrictions
smtpd_helo_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_invalid_helo_hostname,
        reject_non_fqdn_helo_hostname
smtpd_recipient_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_recipient,
        reject_unknown_recipient_domain,
        reject_unlisted_recipient,
        reject_unauth_destination
smtpd_sender_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        reject_non_fqdn_sender,
        reject_unknown_sender_domain
smtpd_relay_restrictions =
        permit_mynetworks,
        permit_sasl_authenticated,
        defer_unauth_destination

# Aliases
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases

# Handing off local delivery to Dovecot's LMTP, and telling it where to store mail
virtual_transport = lmtp:unix:private/dovecot-lmtp

# Virtual domains, users, and aliases
virtual_mailbox_domains = mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
virtual_mailbox_maps = mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
virtual_alias_maps = mysql:/etc/postfix/mysql-virtual-alias-maps.cf,
        mysql:/etc/postfix/mysql-virtual-email2email.cf

# Even more Restrictions and MTA params
disable_vrfy_command = yes
strict_rfc821_envelopes = yes
#smtpd_etrn_restrictions = reject
#smtpd_reject_unlisted_sender = yes
#smtpd_reject_unlisted_recipient = yes
smtpd_delay_reject = yes
smtpd_helo_required = yes
smtp_always_send_ehlo = yes
#smtpd_hard_error_limit = 1
smtpd_timeout = 30s
smtp_helo_timeout = 15s
smtp_rcpt_timeout = 15s
smtpd_recipient_limit = 40
minimal_backoff_time = 180s
maximal_backoff_time = 3h

# Reply Rejection Codes
invalid_hostname_reject_code = 550
non_fqdn_reject_code = 550
unknown_address_reject_code = 550
unknown_client_reject_code = 550
unknown_hostname_reject_code = 550
unverified_recipient_reject_code = 550
unverified_sender_reject_code = 550

# DKIM milter settings
#milter_protocol = 2
#milter_default_action = accept
#smtpd_milters = inet:localhost:12301
#non_smtpd_milters = inet:localhost:12301
EOL
echo "Configured postfix============================"



echo "Configuring virutal mappings=================="

echo "Configuring virutal mailbox domains==========="
sudo cat > /etc/postfix/mysql-virtual-mailbox-domains.cf << EOL
user = mailuser
password = $MAILSERVER_MAILUSER_PASSWORD
hosts = 127.0.0.1
dbname = mailserver
query = SELECT 1 FROM virtual_domains WHERE name='%s'
EOL

echo "Configuring virutal mailboxes================="
sudo cat > /etc/postfix/mysql-virtual-mailbox-maps.cf << EOL
user = mailuser
password = $MAILSERVER_MAILUSER_PASSWORD
hosts = 127.0.0.1
dbname = mailserver
query = SELECT 1 FROM virtual_users WHERE email='%s'
EOL

echo "Configuring virutal aliases==================="
sudo cat > /etc/postfix/mysql-virtual-alias-maps.cf << EOL
user = mailuser
password = $MAILSERVER_MAILUSER_PASSWORD
hosts = 127.0.0.1
dbname = mailserver
query = SELECT destination FROM virtual_aliases WHERE source='%s' UNION ALL SELECT destination FROM virtual_aliases WHERE source='@%d' AND NOT EXISTS (SELECT destination FROM virtual_aliases WHERE source='%s')
EOL

echo "Configuring virutal email sending============="
sudo cat > /etc/postfix/mysql-virtual-email2email.cf << EOL
user = mailuser
password = $MAILSERVER_MAILUSER_PASSWORD
hosts = 127.0.0.1
dbname = mailserver
query = SELECT email FROM virtual_users WHERE email='%s'
EOL

echo "Configured virutal mappings==================="



echo "Reloading postfix============================="
sudo service postfix reload
sudo postmap -q $MAILSERVER_DOMAIN mysql:/etc/postfix/mysql-virtual-mailbox-domains.cf
sudo postmap -q info@$MAILSERVER_DOMAIN mysql:/etc/postfix/mysql-virtual-mailbox-maps.cf
sudo postmap -q test@$MAILSERVER_DOMAIN mysql:/etc/postfix/mysql-virtual-alias-maps.cf
sudo service postfix reload
echo "Configuring postfix complete=================="



echo "Backup files==================================="
sudo cp /etc/postfix/master.cf /etc/postfix/master.cf.orig
echo "Backup original files complete================"



echo "Updating postfix submissions/smpts============"
sudo sed -i '/# -o milter_macro_daemon_name=ORIGINATING/r scripts/postfix_master.txt' /etc/postfix/master.cf
sudo chmod -R o-rwx /etc/postfix
sudo systemctl restart postfix
echo "Updating postfix submissions/smpts complete==="



echo "Postfix automatic setup complete=============="

else

echo "Cancelling installation."

fi

cd
cd mailserver
